# -*- coding: utf-8 -*-
"""SmartCafe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eC8N4PjPd9AzSVxgJXJcRf1_kana77Y0
"""

#s-1

print('='*70)
print(' '*30, 'SMART CAFE', ' '*30)
print('='*70)

cafe_menu= {
    "ESPRESSO":{"Price":120,"Category":"Beverages"},
    "COKE":{"Price":80,"Category":"Beverages"},
    "CAPPUCCINO":{"Price":150,"Category":"Beverages"},
    "CHOCOLATE SHAKE":{"Price":120,"Category":"Beverages"},
    "CHEESE BURGER":{"Price":180,"Category":"Snacks"},
    "FRENCH FRIES":{"Price":90,"Category":"Snacks"},
    "PIZZA":{"Price":250,"Category":"Snacks"},
    "MOMOS":{"Price":120,"Category":"Snacks"},
    "CHOCO LAVA CAKE":{"Price":140,"Category":"Desserts"},
    "ICE CREAM":{"Price":50,"Category":"Desserts"}
}

print('\n \n',"-"*32, 'MENU', "-"*32)
print('\n')
for item, details in cafe_menu.items():
  print(f"{item:<20} Rs.{details['Price']} ({details['Category']})")
  print("-"*70)

#s-2

customer_cart=[]

while True:
  item=input("Enter the items name (or 'done' to finish)").upper()

  if item=="DONE":
    break

  if item in cafe_menu:
        quantity=input("Enter quantity: ")

        if quantity.isdigit() and int(quantity)>0:
          quantity=int(quantity)

          for i in range(quantity):
            customer_cart.append(item)

          print(f"{quantity} x {item} added to cart.")

        else:
          print("INVALID QUANTITY!! please enter valid number")
  else:
    print("Item not available!")


if len(customer_cart)==0:
  print("\nNo items ordered.")
  print("THANK YOU!")

else:



#s-3

  total_bill=0
  category_set=set()
  item_count={}

  for item in customer_cart:
    item_count[item]=item_count.get(item,0)+1
    category_set.add(cafe_menu[item]["Category"])

  for item, qty in item_count.items():
    price=cafe_menu[item]["Price"]
    amount=price*qty
    total_bill += amount

  Subtotal = total_bill

  combo_discount=0

  if len(category_set)==3:
    combo_discount=50
    total_bill -= combo_discount
    print("Combo Discount Applied: Rs.50")


#s-4

  coupon_discount=0
  coupon = input("\nEnter Coupon Code (Press Enter to skip): ").strip()
  if coupon=="WELCOME10":
    coupon_discount=total_bill*0.10
    total_bill-=coupon_discount
    print("Coupon applied successfully.")
    print(f"Coupon Discount (10%): -Rs.{coupon_discount:.2f}")

  elif coupon != "":
    print("Invalid Coupon Code applied. Continuing with original bill.")

  total_after_coupon = total_bill
  def add_gst(total):
    gst = total * 0.05
    grand_total =  total + gst
    return gst, grand_total


  gst_amount, grand_total = add_gst(total_after_coupon)

#final

  print("\n" + "=" *70)
  print(" "*30, "FINAL BILL ")
  print("=" *70)


  print(f"{'item':<20} {'qty':<8} {'amount'}")
  print("-"*70)

  for item, qty in item_count.items():

      amount = qty * cafe_menu[item]["Price"]

      print(f"{item:<20}{qty:<8}Rs.{amount}")

  print("-"*70)

  print(f"Subtotal                          : Rs.{Subtotal:.2f}")

  if combo_discount > 0:
    print(f"Combo Discount                    : -Rs.{combo_discount:.2f}")

  else:
    print(f"Combo Discount                    : Rs.0.00")

  print(f"Coupon Discount                   : -Rs.{coupon_discount:.2f}")
  print(f"Amount before GST                 : Rs.{total_after_coupon:.2f}")
  print(f"GST (5%)                          : Rs.{gst_amount:.2f}")

  print("-"*70)
  print(f"Grand Total                       : Rs.{grand_total:.2f}")
  print("="*70)

  print(f"Categories Ordered From           : {category_set}")

  print("-"*70)
  print("\n" , " "*17 , "THANK YOU FOR VISITING SMART CAFE!!")
  print('='*70)